=== RicardoAndreSantos/Structured-Document-Processing-/PDE - Trabalho1/DTD/livro_receitas.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT livro_receitas (cabeçalho, parte)>

<!ELEMENT cabeçalho (titulo_do_conjunto_de_receitas+, autores+, data_publicaçao , resumo?)>
<!ELEMENT titulo_do_conjunto_de_receitas (#PCDATA)>
<!ELEMENT autores (#PCDATA)>
<!ELEMENT data_publicaçao (#PCDATA)>
<!ELEMENT resumo (#PCDATA)>


<!ELEMENT parte (titulo , introducao? , refer_url? , secçao* )>
<!ATTLIST parte 
	tipo ID #REQUIRED>
	
<!ELEMENT secçao (titulo , introducao? , refer_url? , sub_secçao* )>
<!ATTLIST secçao 
	tipo ID #REQUIRED>

<!ELEMENT sub_secçao (titulo , introducao? , refer_url? , receita+)>
<!ATTLIST sub_secçao 
	tipo ID #REQUIRED>

<!ELEMENT introducao (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>

<!ELEMENT receita (lista_ingredientes+ , nome+ , tempo? , calorias? , refer_url? , descriçao)>
<!ATTLIST receita 
	id_receita ID #REQUIRED
	custo ( barato | médio | caro ) #IMPLIED
	dificuldade (simples | médio | difícil) #IMPLIED
	categoria CDATA #IMPLIED>

<!ELEMENT lista_ingredientes (ingrediente+)>

<!ELEMENT ingrediente (nome , (quantidade , unidade)?)>
<!ELEMENT quantidade (#PCDATA)>
<!ELEMENT unidade (#PCDATA)>

<!ATTLIST ingrediente 
	id_ingrediente ID #REQUIRED >

<!ELEMENT nome (#PCDATA)>
<!ELEMENT tempo (#PCDATA)>
<!ELEMENT calorias (#PCDATA)>

<!ELEMENT descriçao (lista_passos | texto)>

<!ELEMENT lista_passos (passos+)>
<!ELEMENT passos (#PCDATA | refer_url | refer_receita | refer_ingrediente)*>

<!ELEMENT texto (#PCDATA | refer_url  | refer_receita | refer_ingrediente)*>
	
<!ELEMENT refer_url EMPTY>
<!ATTLIST refer_url
	url CDATA #IMPLIED>
	
<!ELEMENT refer_ingrediente EMPTY>
<!ATTLIST refer_ingrediente
	ingrediente IDREF #REQUIRED>
	
<!ELEMENT refer_receita EMPTY>
<!ATTLIST refer_receita
	receita IDREF #REQUIRED>

=== RicardoAndreSantos/Structured-Document-Processing-/PDE - Trabalho1/DTD/dtd_livro_receitas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE livro_receitas SYSTEM "livro_receitas.dtd">

<livro_receitas>

	<cabeçalho>
		<titulo_do_conjunto_de_receitas>Livro de Receitas</titulo_do_conjunto_de_receitas>
		<autores>Ricardo Santos</autores>
		<data_publicaçao>22/10/2017</data_publicaçao>
		<resumo>Receitas rápidas e fáceis de confecionar</resumo>
	</cabeçalho>
	
	<parte tipo="sobremesas">
		<titulo>Sobremesas</titulo>
		<introducao>Todo o tipo de sobremesas</introducao>
		<refer_url url="http://www.google.com/imagemSobremesas"/>
		
		<secçao tipo="semi-frios">
			<titulo>Semi-Frios</titulo>
			<introducao>Sobremesas frias</introducao>
			
			<sub_secçao tipo="bolacha">
				<titulo>Bolos com bolacha</titulo>
				<introducao>Sobremesas com bolacha</introducao>
				
				<receita id_receita="BoloDeBolacha" dificuldade="médio" custo="médio" categoria="sobremesa" >
					<lista_ingredientes>
			
						<ingrediente id_ingrediente="bolachaMaria">
							<nome>Bolacha Maria</nome>
							<quantidade> 3 </quantidade>
						    <unidade> pacotes </unidade>
						</ingrediente>

						<ingrediente id_ingrediente="açucar" >
							<nome>Açucar</nome>
							<quantidade> 200 </quantidade>
						    <unidade> gramas </unidade>
						</ingrediente>
	
					</lista_ingredientes>
		
					<nome>Bolo bolacha</nome>
					<tempo>50 minutos</tempo>
					<calorias>500</calorias>

					<descriçao>
						<lista_passos>
							<passos> Triturar a bolacha maria. <refer_ingrediente ingrediente="bolachaMaria"/>  </passos>
						    <passos> Preparar as natas como podemos ver em: <refer_url url="http://www.google.com/imagemNatas"/> </passos>
						 </lista_passos>
					</descriçao>
				</receita>
			</sub_secçao>
		</secçao>	
		
		<!--  OUTRA RECEITA -->
		
		<secçao tipo="bolos">
		<titulo>Bolos</titulo>
		<introducao>Todo o tipo de bolos</introducao>
		
			<sub_secçao tipo="iogurte">
				<titulo>Iogurte</titulo>
				<introducao>Bolos com iogurte</introducao>
				
				<receita id_receita="BoloDeIogurte" dificuldade="médio" custo="barato" categoria="sobremesa">
					<lista_ingredientes>
						<ingrediente id_ingrediente="natas" >
							<nome>Natas</nome>
							<quantidade> 2 </quantidade>
						    <unidade> pacotes </unidade>
						</ingrediente>
					</lista_ingredientes>
					
					<nome>Bolo de iogurte</nome>
					<tempo>Rápido</tempo>
					<calorias>400</calorias>
					
					<descriçao>	
						<texto>
						Utilizar as natas <refer_ingrediente ingrediente="natas"/>. Utilizar a preparção descrita na receita de bolo de bolacha <refer_receita receita="BoloDeBolacha" />.
						</texto>
					</descriçao>
				</receita>
			</sub_secçao>
		</secçao>
	</parte>
</livro_receitas>

=== RicardoAndreSantos/Structured-Document-Processing-/PDE -  Trabalho 3/dtd_livro_receitas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="rdf_livro_receitas.xsl"?>
<!DOCTYPE livro_receitas SYSTEM "livro_receitas.dtd">

<livro_receitas>

	<cabeçalho>
		<titulo_do_conjunto_de_receitas>Livro de Receitas</titulo_do_conjunto_de_receitas>
		<autores>Ricardo Santos</autores>
		<data_publicaçao>2017/10/22</data_publicaçao>
		<resumo>Receitas rápidas e fáceis de confecionar</resumo>
	</cabeçalho>
	
	<corpo>
		<parte tipo="sobremesas">
			<titulo>Sobremesas</titulo>
			<introducao>Todo o tipo de sobremesas.</introducao>
			<!--  <refer_url url="http://www.google.com/imagemSobremesas"/> -->
			
			<secçao tipo="semi-frios">
				<titulo>Semi-Frios</titulo>
				<introducao>Sobremesas frias.</introducao>
				
				<sub_secçao tipo="bolacha">
					<titulo>Bolos com bolacha</titulo>
					<introducao>Todo o tipo de sobremesas com bolacha.</introducao>
					
					<receita id_receita="BoloDeBolacha" dificuldade="médio" custo="médio" categoria="sobremesa" tempo="50 minutos" >
						
						<nome>Bolo de bolacha</nome>
						<calorias>500</calorias>
						
						<lista_ingredientes>
							<ingrediente id_ingrediente="bolachaMaria">
								<nome>Bolacha Maria</nome>
								<quantidade> 3 </quantidade>
							    <unidade> pacotes </unidade>
							</ingrediente>
	
							<ingrediente id_ingrediente="açucar" >
								<nome>Açucar</nome>
								<quantidade> 200 </quantidade>
							    <unidade> gramas </unidade>
							</ingrediente>
		
						</lista_ingredientes>
	
						<refer_url url="bolo_bolacha.jpg" alt="Bolacha"/>
	
						<descriçao>
							<lista_passos>
								<passo>  Triturar a  <refer_ingrediente ingrediente="bolachaMaria"/> na trituradora.  </passo>
							    <passo> Preparar as natas até atingir a consistência pretendida.  </passo>
							    <passo> De seguida, misturar com o <refer_ingrediente ingrediente="açucar"/>. </passo>
							    <passo> (Apenas para testar a navegação - <refer_receita receita="BoloDeIogurte"/> ) . </passo>
							 </lista_passos>
						</descriçao>
					</receita>
				</sub_secçao>
			</secçao>	
			
			<!--  OUTRA RECEITA -->
			
			<secçao tipo="bolos">
			<titulo>Bolos</titulo>
			<introducao>Todo o tipo de bolos.</introducao>
			
				<sub_secçao tipo="iogurte">
					<titulo>Bolos com Iogurte</titulo>
					<introducao>Bolos utilizando iogurte.</introducao>
					
					<receita id_receita="BoloDeIogurte" dificuldade="médio" custo="barato" categoria="sobremesa" tempo="rápido">
					
						<nome>Bolo de iogurte</nome>
						<calorias>400</calorias>
						
						<lista_ingredientes>
							<ingrediente id_ingrediente="natas" >
								<nome>Natas</nome>
								<quantidade> 2 </quantidade>
							    <unidade> pacotes </unidade>
							</ingrediente>
						</lista_ingredientes>
						
						<refer_url url="bolo_iogurte.jpg" alt="iogurte"/>
						
						<descriçao>	
							<texto>
								Colocar as  <refer_ingrediente ingrediente="natas"/> dentro de um recipiente. De seguida, deve de ser usada a preparação descrita na receita de <refer_receita receita="BoloDeBolacha" /> .
							</texto>
						</descriçao>
					</receita>
				</sub_secçao>
			</secçao>
		</parte>
		
	</corpo>
</livro_receitas>
