=== RicardoAndreSantos/Structured-Document-Processing-/PDE - Trabalho1/XSD/livro_receitas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="livro_receitas" 
		xmlns:tns="livro_receitas" 
		elementFormDefault="qualified">
		
	<element name="livro_receitas" type="tns:livro_receitas" />
		
		<complexType name="livro_receitas">
			<sequence>
				<element name="cabeçalho" type="tns:cabeçalho" maxOccurs="1"
					minOccurs="1"></element>
				<element name="parte" type="tns:parte" maxOccurs='unbounded'
					minOccurs="1"></element>
			</sequence>
		</complexType>
		
		<complexType name="cabeçalho">
			<sequence>
				<element name="titulo_do_conjunto_de_receitas" type="string" minOccurs="1" maxOccurs='unbounded'></element>
				<element name="autores" type="string" minOccurs="1" maxOccurs='unbounded'></element>
				<element name="data_publicaçao" type="date" minOccurs="1" maxOccurs="1" ></element>
				<element name="resumo" type="string" minOccurs="0" maxOccurs="1"></element>
			</sequence>
		</complexType>
		
		
		<complexType name="parte">
			<sequence>
				<element name="titulo" type="string" minOccurs="1" maxOccurs="1"></element>
				<element name="introduçao" type="string" minOccurs="0" maxOccurs="1"></element>
				<element name="refer_url" type="tns:refer_url" minOccurs="0" maxOccurs="1"></element>
				<element name="secçao" type="tns:secçao" minOccurs="0" maxOccurs='unbounded'></element>
			</sequence>
			<attribute use="required" name="tipo" type="ID"/>
		</complexType>
	
		
		<complexType name="secçao">
			<sequence>
				<element name="titulo" type="string" minOccurs="1" maxOccurs="1"></element>
				<element name="introduçao" type="string" minOccurs="0" maxOccurs="1"></element>
				<element name="refer_url" type="tns:refer_url" minOccurs="0" maxOccurs="1"></element>
				<element name="sub_secçao" type="tns:sub_secçao" minOccurs="0" maxOccurs='unbounded'></element>
			</sequence>
		<attribute use="required" name="tipo" type="ID"/>
		</complexType>
		
		<complexType name="sub_secçao">
			<sequence>
				<element name="titulo" type="string" minOccurs="1" maxOccurs="1"></element>
				<element name="introduçao" type="string" minOccurs="0" maxOccurs="1"></element>
				<element name="refer_url" type="tns:refer_url" minOccurs="0" maxOccurs="1"></element>
				<element name="receita" type="tns:receita" minOccurs="1" maxOccurs='unbounded'></element>
			</sequence>
		<attribute use="required" name="tipo" type="ID"/>
		</complexType>
		
		<complexType name="receita">
			<sequence>
				<element name="lista_ingredientes" type="tns:lista_ingredientes" minOccurs="1" maxOccurs="1"></element>
				<element name="nome" type="string" minOccurs="1" maxOccurs="1"></element>
				<element name="tempo" type="string" minOccurs="0" maxOccurs="1"></element>
				<element name="calorias" type="positiveInteger" minOccurs="0" maxOccurs="1"></element>
				<element name="refer_url" type="tns:refer_url" minOccurs="0" maxOccurs="1"></element>
				<element name="descriçao" type="tns:descriçao" minOccurs="1" maxOccurs="1"></element>
			</sequence>
			<attribute name="id_receita" type="ID" use="required" />
			<attribute name="custo" use="optional" >
				<simpleType>
					<restriction base="string">
						<pattern value="barato|médio|caro"/>
					</restriction>
				</simpleType>
			</attribute>
			<attribute name="dificuldade" use="optional" >
				<simpleType>
					<restriction base="string">
						<pattern value="fácil|médio|difícil"/>
					</restriction>
				</simpleType>
			</attribute>
			<attribute name="categoria" type="string" use="optional"/>
		</complexType>
		
		<complexType name="lista_ingredientes">
			<sequence>
				<element name="ingrediente" type="tns:ingrediente" minOccurs="1" maxOccurs='unbounded'></element>
			</sequence>
		</complexType>
		
		<complexType name="ingrediente">
			<sequence>
				<element name="nome" type="string" minOccurs="1" maxOccurs="1"></element>
				<element name="quantidade" type="float" minOccurs="0" maxOccurs="1"></element>
				<element name="unidade" type="string" minOccurs="0" maxOccurs="1"></element>
			</sequence>
			<attribute name="id_ingrediente" type="ID" use="required" />
		</complexType>
		
		<complexType name="descriçao">
			<choice>
				<element name="lista_passos" type="tns:lista_passos"></element>
				<element name="texto" type="tns:texto"> </element>
			</choice>
		</complexType>	
		
		<complexType name="lista_passos">
			<sequence>
				<element name="passos" type="tns:passos" minOccurs="1" maxOccurs='unbounded'/> 
			</sequence>
		</complexType>
		
		<complexType name="passos" mixed="true">
			<all>
				<element name="refer_url" type="tns:refer_url" minOccurs="0"/>
				<element name="refer_ingrediente" type="tns:refer_ingrediente" minOccurs="0"/>
				<element name="refer_receita" type="tns:refer_receita" minOccurs="0"/>				
			</all>
		</complexType>
		
		<complexType name="texto" mixed="true">
			<all>
				<element name="refer_url" type="tns:refer_url" minOccurs="0"/>
				<element name="refer_ingrediente" type="tns:refer_ingrediente" minOccurs="0"/>
				<element name="refer_receita" type="tns:refer_receita" minOccurs="0"/>				
			</all>
		</complexType>		
		
		<complexType name="refer_url">
			<attribute 
				name="url" 
				type="anyURI"
				use="required"/>
		</complexType>
		
		<complexType name="refer_ingrediente">
			<attribute
				name="ingrediente"
				type="IDREF"
				use="required"/>
		</complexType>
		
		<complexType name="refer_receita">
			<attribute
				name="receita"
				type="IDREF"
				use="required"/>
		</complexType>
		
		
		
</schema>

=== RicardoAndreSantos/Structured-Document-Processing-/PDE - Trabalho1/XSD/xsd_livro_receitas.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:livro_receitas xmlns:tns="livro_receitas" 
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
					xsi:schemaLocation="livro_receitas livro_receitas.xsd">
		
	<tns:cabeçalho>
		<tns:titulo_do_conjunto_de_receitas>Livro de Receitas</tns:titulo_do_conjunto_de_receitas>
		<tns:autores>Ricardo Santos</tns:autores>
		<tns:data_publicaçao>2017-12-25</tns:data_publicaçao>
		<tns:resumo>Receitas rápidas e fáceis de confecionar</tns:resumo>
	</tns:cabeçalho>
	
	
	<tns:parte tipo="sobremesa">
		<tns:titulo>Sobremesas</tns:titulo>
		<tns:introduçao>Todo o tipo de sobremesas</tns:introduçao>
		<tns:refer_url url="http://www.google.com/imagemSobremesas"/>
		
			<tns:secçao tipo="semi-frios">
				<tns:titulo>Semi-Frios</tns:titulo>
				<tns:introduçao>Sobremesas frias</tns:introduçao>
				
				<tns:sub_secçao tipo="bolacha">
					<tns:titulo>Bolos com bolacha</tns:titulo>
					<tns:introduçao>Sobremesas com bolacha</tns:introduçao>
					
					<tns:receita id_receita="BoloDeBolacha" dificuldade="médio" custo="médio" categoria="sobremesa">
						<tns:lista_ingredientes>
						
							<tns:ingrediente id_ingrediente="bolachaMaria">
								<tns:nome>Bolacha Maria</tns:nome>
								<tns:quantidade>3</tns:quantidade>
								<tns:unidade>pacotes</tns:unidade>
							</tns:ingrediente>
							
							<tns:ingrediente id_ingrediente="açucar">
								<tns:nome>Açucar</tns:nome>
								<tns:quantidade>200</tns:quantidade>
								<tns:unidade>gramas</tns:unidade>
							</tns:ingrediente>
						</tns:lista_ingredientes>
						
						<tns:nome>Bolo de Bolacha</tns:nome>
						<tns:tempo>50 minutos</tns:tempo>
						<tns:calorias>500</tns:calorias>
						
						<tns:descriçao>
							<tns:lista_passos>
								<tns:passos> Triturar a bolacha maria. <tns:refer_ingrediente ingrediente="bolachaMaria"/> </tns:passos>
								<tns:passos>Preparar as natas como podemos ver em: <tns:refer_url url="http://www.google.com/imagemNatas"/></tns:passos>	
							</tns:lista_passos>
						</tns:descriçao>
					
					</tns:receita>	
				</tns:sub_secçao>
		</tns:secçao>
		
		<!-- OUTRA RECEITA -->
		
		<tns:secçao tipo="bolos">
			<tns:titulo>Bolos</tns:titulo>
			<tns:introduçao>Todo o tipo de bolos</tns:introduçao>
			
			<tns:sub_secçao tipo="iogurte">
					<tns:titulo>Iogurte</tns:titulo>
					<tns:introduçao>Bolos com iogurte</tns:introduçao>
					
					<tns:receita id_receita="BoloDeIogurte" dificuldade="médio" custo="barato" categoria="sobremesa">
						<tns:lista_ingredientes>
							<tns:ingrediente id_ingrediente="natas">
								<tns:nome>Natas</tns:nome>
								<tns:quantidade>2</tns:quantidade>
								<tns:unidade>pacotes</tns:unidade>
							</tns:ingrediente>
						</tns:lista_ingredientes>
						
						<tns:nome>Bolo de iogurte</tns:nome>
						<tns:tempo>Rápido</tns:tempo>
						<tns:calorias>300</tns:calorias>
						
						<tns:descriçao>
							<tns:texto>
								Utilizar as natas <tns:refer_ingrediente ingrediente="natas"/>. Utilizar a preparção descrita na receita de bolo de bolacha <tns:refer_receita receita="BoloDeBolacha"/>.
							</tns:texto>
						</tns:descriçao>
					</tns:receita>
			</tns:sub_secçao>	
		</tns:secçao>
	</tns:parte>
</tns:livro_receitas>
